// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/interceptor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The intercepted API call info
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Url    string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// Call 1: The input sent by the agent
	RequestBody []byte `protobuf:"bytes,5,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	// Call 2: The output returned to the agent
	ResponseStatus int32  `protobuf:"varint,6,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseBody   []byte `protobuf:"bytes,7,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	Timestamp      int64  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	mi := &file_proto_v1_interceptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_interceptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_interceptor_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TransactionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TransactionEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TransactionEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TransactionEvent) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *TransactionEvent) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *TransactionEvent) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *TransactionEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_proto_v1_interceptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_interceptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_interceptor_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_v1_interceptor_proto protoreflect.FileDescriptor

const file_proto_v1_interceptor_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/interceptor.proto\x12\x06rpc.v1\"\x85\x02\n" +
	"\x10TransactionEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12!\n" +
	"\frequest_body\x18\x05 \x01(\fR\vrequestBody\x12'\n" +
	"\x0fresponse_status\x18\x06 \x01(\x05R\x0eresponseStatus\x12#\n" +
	"\rresponse_body\x18\a \x01(\fR\fresponseBody\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"I\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2c\n" +
	"\x12TransactionService\x12M\n" +
	"\x12StreamTransactions\x12\x18.rpc.v1.TransactionEvent\x1a\x1b.rpc.v1.TransactionResponse(\x01B%Z#github.com/poc-amp/backend/proto/v1b\x06proto3"

var (
	file_proto_v1_interceptor_proto_rawDescOnce sync.Once
	file_proto_v1_interceptor_proto_rawDescData []byte
)

func file_proto_v1_interceptor_proto_rawDescGZIP() []byte {
	file_proto_v1_interceptor_proto_rawDescOnce.Do(func() {
		file_proto_v1_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_interceptor_proto_rawDesc), len(file_proto_v1_interceptor_proto_rawDesc)))
	})
	return file_proto_v1_interceptor_proto_rawDescData
}

var file_proto_v1_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_interceptor_proto_goTypes = []any{
	(*TransactionEvent)(nil),    // 0: rpc.v1.TransactionEvent
	(*TransactionResponse)(nil), // 1: rpc.v1.TransactionResponse
}
var file_proto_v1_interceptor_proto_depIdxs = []int32{
	0, // 0: rpc.v1.TransactionService.StreamTransactions:input_type -> rpc.v1.TransactionEvent
	1, // 1: rpc.v1.TransactionService.StreamTransactions:output_type -> rpc.v1.TransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_interceptor_proto_init() }
func file_proto_v1_interceptor_proto_init() {
	if File_proto_v1_interceptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_interceptor_proto_rawDesc), len(file_proto_v1_interceptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_interceptor_proto_goTypes,
		DependencyIndexes: file_proto_v1_interceptor_proto_depIdxs,
		MessageInfos:      file_proto_v1_interceptor_proto_msgTypes,
	}.Build()
	File_proto_v1_interceptor_proto = out.File
	file_proto_v1_interceptor_proto_goTypes = nil
	file_proto_v1_interceptor_proto_depIdxs = nil
}
