//go:build ignore

// This file is a placeholder showing the expected structure of generated eBPF bindings.
// The actual bindings will be generated by running: go generate ./...
// This file is excluded from the build with the 'ignore' build tag.

package ebpf

import "github.com/cilium/ebpf"

// bpfObjects contains all objects after they have been loaded into the kernel.
// This struct will be auto-generated by bpf2go.
type bpfObjectsPlaceholder struct {
	// Programs
	CaptureHttp     *ebpf.Program `ebpf:"capture_http"`
	TraceTcpSendmsg *ebpf.Program `ebpf:"trace_tcp_sendmsg"`
	TraceTcpRecvmsg *ebpf.Program `ebpf:"trace_tcp_recvmsg"`

	// Maps
	AmpContainers *ebpf.Map `ebpf:"amp_containers"`
	Rb            *ebpf.Map `ebpf:"rb"`
}
